language: swift
xcode_project: ProjectSetupDemo/ProjectSetupDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: ProjectSetupDemo
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 11
